all:
data:
  source: assets
  entities: ["AAPL", "MSFT", "AMZN", "GOOGL", "TSLA"] # entities are called 'tickers' in finance
  end_date: # expecting a %Y-%m-%d string, if None then taken as today
  duration: ['weeks',1000] #in datetime args format
  rolling_count: 11 #including n+1 in that case

  ## add something for feature engineering.
model:
  type: Sequential
  training:
    loss: MSELoss
    n_epochs: 100
    batch_size: 32
    max_increases: 100
    learning_rate: 
    optimiser: Adam
  architecture:
    - Conv2d:
        args: [1, 8, 3, 1, 1]  # input_channels, output_channels, kernel_size, stride, padding
        # 8 x 10 x 5
    - BatchNorm2d:
        args: [8]
    - ReLU:
        inplace: false    
    - Flatten: {}
    - Linear:
        args: [400, 128]  # output from conv layers flattened
    - ReLU:
        inplace: false
    - Linear:
        args: [128, 256]
    - ReLU:
        inplace: false
    - Linear:
        args: [256,128]
    - ReLU:
        inplace: false
    - Linear:
        args: [128,64]
    - ReLU:
        inplace: false
    - Linear:
        args: [64, 5]  # final output to match the 1x5 target
